apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitor.componentLabels" (dict "component" "blackbox-exporter" "context" $) | nindent 4 }}
spec:
  selector:
    {{- include "monitor.selectorLabels" (dict "component" "blackbox-exporter" "context" $) | nindent 4 }}
  ports:
    - port: 9115
      targetPort: 9115
      name: http
  type: ClusterIP
