apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitor.componentLabels" (dict "component" "grafana" "context" $) | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
