apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-exporter-web-templates
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitor.componentLabels" (dict "component" "monitor-exporter" "context" $) | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "web_templates/*.html" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
