{{- if .Values.dbSecrets.postgresPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: monitor-db-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitor.componentLabels" (dict "component" "grafana" "context" $) | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.dbSecrets.postgresPassword | quote }}
{{- end }}
