{{- if or .Values.tokens.gitlab .Values.tokens.sonar .Values.tokens.gitlabTrigger .Values.tokens.triggerSharedSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: monitor-tokens
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitor.componentLabels" (dict "component" "monitor-exporter" "context" $) | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.tokens.gitlab }}
  {{- end }}
  {{- if .Values.tokens.sonar }}
  {{- end }}
  {{- if .Values.tokens.gitlabTrigger }}
  {{- end }}
  {{- if .Values.tokens.triggerSharedSecret }}
  {{- end }}
{{- end }}
