apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-to-graph-code
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitor.componentLabels" (dict "component" "grafana" "context" $) | nindent 4 }}
data:
  main.py: |
{{ .Files.Get "smtp_to_graph.py" | indent 4 }}
