apiVersion: v1
kind: Service
metadata:
  name: ssl-exporter
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitor.componentLabels" (dict "component" "ssl-exporter" "context" $) | nindent 4 }}
spec:
  selector:
    {{- include "monitor.selectorLabels" (dict "component" "ssl-exporter" "context" $) | nindent 4 }}
  ports:
    - port: 9117
      targetPort: 9117
      name: http
  type: ClusterIP
